### ISSUE TITLE
RaCoCo fails when tests passed

### ISSUE THREAD

**Issue by melezhik** [atroxaper/raku-RaCoCo#11]
Hi!
I am not sure if this a RaCoCo issue, however - http://sparrowhub.io:2222/report/37

HTH

Aleksei

**Comment by atroxaper** [comment]
Hello. Thank you for your interest in RaCoCo.

As I see the log, there is a warning from prove6 about `t/03-warn.t`. This means that prove6 returned nonzero exit code and RaCoCo failed too, accordingly.

In general, such warnings are if a test file uses subtests with output to STDOUT. It is known issue (https://github.com/Raku/tap-harness6/issues/33) and they decided that it is a feature.

But in our situation with `Timezones::ZoneInfo`, it is because some module's output mess with TAP specific output. Anyway, prove6 returns a nonzero exit code. On the other way, `prove t --exec "raku -Ilib"` work like a charm with this TAP output.

@melezhik what do you think, is it an issue?

**Comment by melezhik** [comment]
@atroxaper  thanks for explanation, looks like this is `Timezones::ZoneInfo` issue, not RaCoCo, that's ok.
I am using RaCoCo as a part of SparkyCI. This is great tool, thanks!

**Comment by atroxaper** [comment]
@melezhik Thank you!

**Comment by Leont** [comment]
> In general, such warnings are if a test file uses subtests with output to STDOUT. It is known issue (https://github.com/Raku/tap-harness6/issues/33) and they decided that it is a feature.

If you don't want this behavior, you can always pass `--loose` to `prove6`.

**Comment by atroxaper** [comment]
@Leont Thank you! I didn’t see the option in the readme. And don’t see now too :)
