### ISSUE TITLE
Including ./lib does not work

### ISSUE THREAD

**Issue by wbiker** [atroxaper/raku-RaCoCo#2]
Hi,
I want to use racoco to get a test coverage of my module but unfortunately, it fails to run my tests because the local lib folder is not in the search path:
```raku
racoco --lib=./lib

===SORRY!=== Error while compiling /home/wolf/repos/module2rpm/t/00-tar.t
Could not find Module2Rpm::Archive::Tar in:
    inst#/home/wolf/.raku
    inst#/home/wolf/.rakubrew/versions/moar-2020.12/install/share/perl6/site
    inst#/home/wolf/.rakubrew/versions/moar-2020.12/install/share/perl6/vendor
    inst#/home/wolf/.rakubrew/versions/moar-2020.12/install/share/perl6/core
    ap#
    nqp#
    perl5#
```
It does not work without --lib and not with it. Only using the RAKULIB environment variable works.

**Comment by atroxaper** [comment]
@wbiker Hello. Thank you for your interest in RaCoCo. As I understand, generally, you run your tests something like `prove6 -Ilib`, because you do not include `use lib ‘lib’;` in your test files. As RaCoCo readme says, it uses `prove6` command to run tests instead. In your case, please use `racoco --exec=‘prove6 -Ilib’` 

I’m going to add Frequently Problems sections in the readme at least.

**Comment by wbiker** [comment]
Thanks @atroxaper,
Sorry, for not reading your docs carefully enough. I thought the --lib parameter is used for that and did not think of exec. It might be a good idea to add `racoco --exec='prove6 -Ilib' for people like me rushing through the documentation.
